// Stimulus mapping for Spatial Navigation Task
const stimulusMapping = {
    easy: [
        { id: "easy_001", file: "stimuli/1.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_002", file: "stimuli/2.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_003", file: "stimuli/3.png", egocentric_correct: "down", allocentric_correct: "up" },
        { id: "easy_004", file: "stimuli/4.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_005", file: "stimuli/5.png", egocentric_correct: "right", allocentric_correct: "up" },
        { id: "easy_006", file: "stimuli/6.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_007", file: "stimuli/7.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_008", file: "stimuli/8.png", egocentric_correct: "down", allocentric_correct: "up" },
        { id: "easy_009", file: "stimuli/9.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_010", file: "stimuli/10.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "easy_011", file: "stimuli/11.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "easy_012", file: "stimuli/12.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "easy_013", file: "stimuli/13.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_014", file: "stimuli/14.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_015", file: "stimuli/15.png", egocentric_correct: "right", allocentric_correct: "right" },
        { id: "easy_016", file: "stimuli/16.png", egocentric_correct: "up", allocentric_correct: "right" },
        { id: "easy_017", file: "stimuli/17.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_018", file: "stimuli/18.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_019", file: "stimuli/19.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "easy_020", file: "stimuli/20.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "easy_021", file: "stimuli/21.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_022", file: "stimuli/22.png", egocentric_correct: "left", allocentric_correct: "right" },
        { id: "easy_023", file: "stimuli/23.png", egocentric_correct: "up", allocentric_correct: "right" },
        { id: "easy_024", file: "stimuli/24.png", egocentric_correct: "right", allocentric_correct: "left" },
        { id: "easy_025", file: "stimuli/25.png", egocentric_correct: "down", allocentric_correct: "up" },
        { id: "easy_026", file: "stimuli/26.png", egocentric_correct: "down", allocentric_correct: "up" },
        { id: "easy_027", file: "stimuli/27.png", egocentric_correct: "right", allocentric_correct: "left" },
        { id: "easy_028", file: "stimuli/28.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "easy_029", file: "stimuli/29.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "easy_030", file: "stimuli/30.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "easy_031", file: "stimuli/31.png", egocentric_correct: "right", allocentric_correct: "up" },
        { id: "easy_032", file: "stimuli/32.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_033", file: "stimuli/33.png", egocentric_correct: "right", allocentric_correct: "left" },
        { id: "easy_034", file: "stimuli/34.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "easy_035", file: "stimuli/35.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_036", file: "stimuli/36.png", egocentric_correct: "up", allocentric_correct: "down" }
    ],
    hard: [
        { id: "hard_001", file: "stimuli/37.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "hard_002", file: "stimuli/38.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "hard_003", file: "stimuli/39.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_004", file: "stimuli/40.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "hard_005", file: "stimuli/41.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_006", file: "stimuli/42.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_007", file: "stimuli/43.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_008", file: "stimuli/44.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "hard_009", file: "stimuli/45.png", egocentric_correct: "right", allocentric_correct: "down" },
        { id: "hard_010", file: "stimuli/46.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "hard_011", file: "stimuli/47.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "hard_012", file: "stimuli/48.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "hard_013", file: "stimuli/49.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_014", file: "stimuli/50.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_015", file: "stimuli/51.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "hard_016", file: "stimuli/52.png", egocentric_correct: "down", allocentric_correct: "left" },
        { id: "hard_017", file: "stimuli/53.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_018", file: "stimuli/54.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_019", file: "stimuli/55.png", egocentric_correct: "right", allocentric_correct: "left" },
        { id: "hard_020", file: "stimuli/56.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_021", file: "stimuli/57.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_022", file: "stimuli/58.png", egocentric_correct: "right", allocentric_correct: "right" },
        { id: "hard_023", file: "stimuli/59.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "hard_024", file: "stimuli/60.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_025", file: "stimuli/61.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_026", file: "stimuli/62.png", egocentric_correct: "up", allocentric_correct: "right" },
        { id: "hard_027", file: "stimuli/63.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_028", file: "stimuli/64.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_029", file: "stimuli/65.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "hard_030", file: "stimuli/66.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "hard_031", file: "stimuli/67.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "hard_032", file: "stimuli/68.png", egocentric_correct: "down", allocentric_correct: "right" }
    ],
    control: [
        { id: "control_01", file: "stimuli/69.png", egocentric_correct: "right", allocentric_correct: "right" },
        { id: "control_02", file: "stimuli/70.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "control_03", file: "stimuli/71.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "control_04", file: "stimuli/72.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "control_05", file: "stimuli/73.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "control_06", file: "stimuli/74.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "control_07", file: "stimuli/75.png", egocentric_correct: "right", allocentric_correct: "right" },
        { id: "control_08", file: "stimuli/76.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "control_09", file: "stimuli/77.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "control_010", file: "stimuli/78.png", egocentric_correct: "down", allocentric_correct: "down" }
    ]
};