// Stimulus mapping for Spatial Navigation Task
// Files are organized in subfolders: stimuli/easy/, stimuli/hard/, stimuli/control/
const stimulusMapping = {
    easy: [
        { id: "easy_001", file: "stimuli/easy/1.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_002", file: "stimuli/easy/2.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_003", file: "stimuli/easy/3.png", egocentric_correct: "down", allocentric_correct: "up" },
        { id: "easy_004", file: "stimuli/easy/4.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_005", file: "stimuli/easy/5.png", egocentric_correct: "right", allocentric_correct: "up" },
        { id: "easy_006", file: "stimuli/easy/6.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_007", file: "stimuli/easy/7.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_008", file: "stimuli/easy/8.png", egocentric_correct: "down", allocentric_correct: "up" },
        { id: "easy_009", file: "stimuli/easy/9.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_010", file: "stimuli/easy/10.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "easy_011", file: "stimuli/easy/11.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "easy_012", file: "stimuli/easy/12.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "easy_013", file: "stimuli/easy/13.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_014", file: "stimuli/easy/14.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_015", file: "stimuli/easy/15.png", egocentric_correct: "right", allocentric_correct: "right" },
        { id: "easy_016", file: "stimuli/easy/16.png", egocentric_correct: "up", allocentric_correct: "right" },
        { id: "easy_017", file: "stimuli/easy/17.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_018", file: "stimuli/easy/18.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "easy_019", file: "stimuli/easy/19.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "easy_020", file: "stimuli/easy/20.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "easy_021", file: "stimuli/easy/21.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_022", file: "stimuli/easy/22.png", egocentric_correct: "left", allocentric_correct: "right" },
        { id: "easy_023", file: "stimuli/easy/23.png", egocentric_correct: "up", allocentric_correct: "right" },
        { id: "easy_024", file: "stimuli/easy/24.png", egocentric_correct: "right", allocentric_correct: "left" },
        { id: "easy_025", file: "stimuli/easy/25.png", egocentric_correct: "down", allocentric_correct: "up" },
        { id: "easy_026", file: "stimuli/easy/26.png", egocentric_correct: "down", allocentric_correct: "up" },
        { id: "easy_027", file: "stimuli/easy/27.png", egocentric_correct: "right", allocentric_correct: "left" },
        { id: "easy_028", file: "stimuli/easy/28.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "easy_029", file: "stimuli/easy/29.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "easy_030", file: "stimuli/easy/30.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "easy_031", file: "stimuli/easy/31.png", egocentric_correct: "right", allocentric_correct: "up" },
        { id: "easy_032", file: "stimuli/easy/32.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_033", file: "stimuli/easy/33.png", egocentric_correct: "right", allocentric_correct: "left" },
        { id: "easy_034", file: "stimuli/easy/34.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "easy_035", file: "stimuli/easy/35.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "easy_036", file: "stimuli/easy/36.png", egocentric_correct: "up", allocentric_correct: "down" }
    ],
    hard: [
        { id: "hard_001", file: "stimuli/hard/1.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "hard_002", file: "stimuli/hard/2.png", egocentric_correct: "left", allocentric_correct: "up" },
        { id: "hard_003", file: "stimuli/hard/3.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_004", file: "stimuli/hard/4.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "hard_005", file: "stimuli/hard/5.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_006", file: "stimuli/hard/6.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_007", file: "stimuli/hard/7.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_008", file: "stimuli/hard/8.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "hard_009", file: "stimuli/hard/9.png", egocentric_correct: "right", allocentric_correct: "down" },
        { id: "hard_010", file: "stimuli/hard/10.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "hard_011", file: "stimuli/hard/11.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "hard_012", file: "stimuli/hard/12.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "hard_013", file: "stimuli/hard/13.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_014", file: "stimuli/hard/14.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_015", file: "stimuli/hard/15.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "hard_016", file: "stimuli/hard/16.png", egocentric_correct: "down", allocentric_correct: "left" },
        { id: "hard_017", file: "stimuli/hard/17.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_018", file: "stimuli/hard/18.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_019", file: "stimuli/hard/19.png", egocentric_correct: "right", allocentric_correct: "left" },
        { id: "hard_020", file: "stimuli/hard/20.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_021", file: "stimuli/hard/21.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_022", file: "stimuli/hard/22.png", egocentric_correct: "right", allocentric_correct: "right" },
        { id: "hard_023", file: "stimuli/hard/23.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "hard_024", file: "stimuli/hard/24.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_025", file: "stimuli/hard/25.png", egocentric_correct: "up", allocentric_correct: "left" },
        { id: "hard_026", file: "stimuli/hard/26.png", egocentric_correct: "up", allocentric_correct: "right" },
        { id: "hard_027", file: "stimuli/hard/27.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_028", file: "stimuli/hard/28.png", egocentric_correct: "up", allocentric_correct: "down" },
        { id: "hard_029", file: "stimuli/hard/29.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "hard_030", file: "stimuli/hard/30.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "hard_031", file: "stimuli/hard/31.png", egocentric_correct: "left", allocentric_correct: "down" },
        { id: "hard_032", file: "stimuli/hard/32.png", egocentric_correct: "down", allocentric_correct: "right" }
    ],
    control: [
        { id: "control_01", file: "stimuli/control/1.png", egocentric_correct: "right", allocentric_correct: "right" },
        { id: "control_02", file: "stimuli/control/2.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "control_03", file: "stimuli/control/3.png", egocentric_correct: "down", allocentric_correct: "down" },
        { id: "control_04", file: "stimuli/control/4.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "control_05", file: "stimuli/control/5.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "control_06", file: "stimuli/control/6.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "control_07", file: "stimuli/control/7.png", egocentric_correct: "right", allocentric_correct: "right" },
        { id: "control_08", file: "stimuli/control/8.png", egocentric_correct: "up", allocentric_correct: "up" },
        { id: "control_09", file: "stimuli/control/9.png", egocentric_correct: "left", allocentric_correct: "left" },
        { id: "control_010", file: "stimuli/control/10.png", egocentric_correct: "down", allocentric_correct: "down" }
    ]
};
